# Generated by Django 2.1.4 on 2018-12-27 14:32

from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User(first_name="User", last_name="001", email="test@email.com", phone="6091111111", address="331 Donlon Hall", description="test data").save()



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
