# Generated by Django 2.1.1 on 2019-02-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='undergrads_major',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='undergrads_university',
            field=models.CharField(default='', max_length=100),
        ),
    ]
