# Generated by Django 2.1.1 on 2019-03-07 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190307_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='undergrads_major',
        ),
        migrations.RemoveField(
            model_name='user',
            name='undergrads_university',
        ),
    ]
