export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_POST_LIST_START = "GET_POST_LIST_START";
export const GET_POST_LIST_FAIL = "GET_POST_LIST_FAIL";
export const GET_POST_LIST_SUCCESS = "GET_POST_LIST_SUCCESS";

export const GET_POST_DETAIL_START = "GET_POST_DETAIL_START";
export const GET_POST_DETAIL_FAIL = "GET_POST_DETAIL_FAIL";
export const GET_POST_DETAIL_SUCCESS = "GET_POST_DETAIL_SUCCESS";

export const POST_START = "POST_START";
export const POST_FAIL = "POST_FAIL";
export const POST_SUCCESS = "POST_SUCCESS";
