# Generated by Django 2.1.1 on 2019-01-30 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeassignment',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='gradeassignment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='GradeAssignment',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
