# Generated by Django 2.1.1 on 2019-02-03 20:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20190130_0344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment',
            new_name='Post',
        ),
    ]
