# Generated by Django 2.1.1 on 2019-02-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190206_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='relevent_file',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
