# Generated by Django 2.1.1 on 2019-02-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_relevent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='relevent_file',
            field=models.FileField(default=False, upload_to='files/'),
        ),
    ]
