# Generated by Django 2.1.1 on 2019-03-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190213_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='company',
            field=models.CharField(max_length=50),
        ),
    ]
