# Generated by Django 2.1.5 on 2019-03-27 05:16

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190327_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='relevent_file',
            field=models.FileField(blank=True, default=False, storage=django.core.files.storage.FileSystemStorage(location='/media/files'), upload_to=''),
        ),
    ]
