# Generated by Django 2.1.5 on 2019-03-27 05:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190327_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='relevent_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/sdf'), upload_to=''),
        ),
    ]
