# Generated by Django 2.1.5 on 2019-04-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190419_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='semester',
            field=models.CharField(default='[]', max_length=20),
        ),
    ]
