# Generated by Django 2.1.5 on 2019-04-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190419_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='internship',
            field=models.CharField(default='notsure', max_length=10),
        ),
    ]
