# Generated by Django 2.1.5 on 2019-04-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_post_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='notsure', max_length=40),
        ),
    ]
