# Generated by Django 2.1.5 on 2019-04-27 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='relevent_file',
        ),
    ]
