# Generated by Django 2.1.5 on 2019-04-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_post_relevent_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.CharField(default='', max_length=255),
        ),
    ]
